Feat: Implement optional codecov results upload
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -83,3 +83,31 @@ jobs:
           # Check previous step failure
           echo "Error: previous step should have failed ❌"
           exit 1
+
+      # Perform Python project standard tests
+      - name: "Run action: ${{ github.repository }} [Codecov/No token]"
+        id: codecov-notoken
+        uses: ./
+        with:
+          python_version: ${{ env.python_version }}
+          path_prefix: "test-python-project/"
+          tests_path: "tests"
+          codecov_report: true
+
+      - name: "Validate previous step failure"
+        if: steps.codecov-notoken.outcome == 'success'
+        shell: bash
+        run: |
+          # Check previous step failure
+          echo "Error: previous step should have failed ❌"
+          exit 1
+
+      # Perform Python tests with codecov report
+      - name: "Run action: ${{ github.repository }} [Codecov report]"
+        uses: ./
+        with:
+          python_version: ${{ env.python_version }}
+          path_prefix: "test-python-project/"
+          tests_path: "tests"
+          codecov_report: true
+          codecov_token: "${{ secrets.CODECOV_TOKEN }}"
diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -41,11 +41,23 @@ inputs:
     description: "Space separated list of tox environments to run"
     required: false
     type: string
+  CODECOV_REPORT:
+    # Note: by default uses CODECOV_TOKEN in the GitHub environment
+    description: "Upload test coverage using Codecov CLI"
+    required: false
+    type: boolean
+    default: false
+  CODECOV_TOKEN:
+    # Optionally pass a token in explicitly, e.g. from 1Password
+    description: "Token to use for Codecov upload"
+    required: false
+    type: 'string'
 
 runs:
   using: "composite"
   steps:
     - name: "Setup action/environment"
+      id: setup
       shell: bash
       run: |
         # Setup action/environment
@@ -152,10 +164,11 @@ runs:
         echo "Install project and dependencies"
         if [ -f ${{ env.path_prefix }}/pyproject.toml ]; then
             echo "Source: ${{ env.path_prefix }}/pyproject.toml ⬇️"
-            pip install -q "${{ env.path_prefix }}/"
+            pip install --disable-pip-version-check -q "${{ env.path_prefix }}/"
         elif [ -f ${{ env.path_prefix }}/requirements.txt ]; then
           echo "Source: ${{ env.path_prefix }}/requirements.txt ⬇️"
-          pip install -q -r "${{ env.path_prefix }}/requirements.txt"
+          pip install --disable-pip-version-check \
+            -q -r "${{ env.path_prefix }}/requirements.txt"
         fi
 
         echo "Running tests in: ${{ env.tests_path }} 🧪"
@@ -193,3 +206,31 @@ runs:
         name: test_coverage_report-${{ inputs.python_version }}.zip
         path: test_coverage_report-${{ inputs.python_version }}.zip
         retention-days: 90
+
+    - name: "Upload Codecov report"
+      # yamllint disable-line rule:line-length
+      if: inputs.CODECOV_REPORT == 'disabled'
+      shell: bash
+      run: |
+        # Upload Codecov report
+        echo "Installing: codecov_cli ⬇️"
+        pip install --disable-pip-version-check -q codecov_cli
+        if [ -n "${{ inputs.CODECOV_TOKEN }}" ]; then
+          codecovcli upload-process -t "${{ inputs.CODECOV_TOKEN }}"
+        else
+          codecovcli upload-process
+        fi
+        if [ $? -eq 0 ] then
+          echo "## Codecov Report Created 📄" >> "$GITHUB_STEP_SUMMARY"
+        else
+          echo "## Codecov Report Failed ❌" >> "$GITHUB_STEP_SUMMARY"
+        fi
+
+    - name: 'Upload Codecov report'
+      # yamllint disable-line rule:line-length
+      uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
+      if: inputs.CODECOV_REPORT == 'true'
+      with:
+        fail_ci_if_error: true # optional (default = false)
+        token: ${{ inputs.CODECOV_TOKEN }}
+        verbose: true
